version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ai-content-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aicontentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
